import { NAME } from './constants';

export const ADD_PLAYLIST = `${NAME}/ADD_PLAYLIST`;
export const ADD_CREATED_PLAYLIST = `${NAME}/ADD_CREATED_PLAYLIST`;
export const ACTUALIZE_PLAYLIST = `${NAME}/ACTUALIZE_PLAYLIST`;
export const REMOVE_PLAYLIST = `${NAME}/REMOVE_PLAYLIST`;

export const ADD_PLAYLIST_TRACK = `${NAME}/ADD_PLAYLIST_TRACK`;
export const REMOVE_PLAYLIST_TRACK = `${NAME}/REMOVE_PLAYLIST_TRACK`;

export const ADD_FAVORITED_PLAYLIST = `${NAME}/ADD_FAVORITED_PLAYLIST`;
export const ADD_SHARED_PLAYLIST = `${NAME}/ADD_SHARED_PLAYLIST`;
